export const config = {
  version: '1.0.0',
  mode: 'publisher',
  domain: 'https://xn--vb0b562al4gzsfbrm.com',
  displayDomain: '창원피부과.com',
  siteName: '창원피부과.com',
  tagline: '창원·상남동·중동 피부 진료와 시술 정보를 지역별로 정리합니다.',
  publisher: {
    name: '주식회사 지바',
    editorialName: '창원피부과.com 편집팀',
    kakaoUrl: 'https://pf.kakao.com/_xfBcan',
  },
  clinic: {
    name: '',
    legalName: '',
    logo: '',
    kakaoUrl: '',
    phone: '',
    naverBookingUrl: '',
    address: '',
    mapUrl: '',
    openingHours: [],
    specialties: [],
  },
  theme: {
    primary: '#123F39',
    primaryDark: '#0B2E2A',
    primarySoft: '#DDE9E5',
    accent: '#B68D63',
    accentSoft: '#F0E5D8',
    background: '#F7F4EF',
    surface: '#FFFFFF',
    text: '#17201E',
    muted: '#66706C',
    line: '#E3DED6',
  },
  analytics: { ga4Id: '' },
};
